config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "sessions#new"

  resources :users
  resources :listings

  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  get "/signup" => "users#new", as: "sign_up"
  post "/signup" => "users#create"
  get "/mylistings" => "listings#mylistings", as: "my_listings"
end

# resource: book || session || listing || user
# 7 restful routes

# new => a form to a new resource

# create => sending information from new form to create 
# resource

# index => show all the resource

# show => show one particular resource

# edit => to show a form to edit a resource

# update => sending information from edit form to edit 
# resource

# delete => to delete a resource

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	helper_method :current_user

	private
	def current_user
		User.find_by_id(session[:user_id])
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :set_listing, only: [:edit, :update, :show, :destroy]

	def index
		@listings = Listing.all
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.new(listings_params)
		if @listing.save
			redirect_to @listing
		else
			render "new"
		end
	end
	
	def edit
	end

	def update
		if @listing.update(listings_params)
			redirect_to listings_path
		else
			render "edit"
		end
	end

	def show
	end

	def destroy
		if @listing.destroy
			redirect_to listings_path
		else
			redirect_to @listing
		end
	end

	def mylistings
		@listings = current_user.listings
		render "index"
	end

	private
	def listings_params
		params.require(:listing).permit(:name, :location, :price)
	end

	def set_listing
		@listing = Listing.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user
			session[:user_id] = @user.id
			redirect_to listings_path
		else
			render "new"
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(users_params)
		if @user.save
			redirect_to root_path
		else
			render "new"
		end
	end

	private
	def users_params
		params.require(:user).permit(:email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |l| %>
	<%= l.text_field :name %>
	<%= l.text_field :location %>
	<%= l.number_field :price %>
	<%= l.submit %>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render partial: "form" %>

app/views/listings/index.html.erb
<h1>Listings Index</h1>

<% @listings.each do |l| %>
	<%= link_to l.name, listing_path(l) %><br>
<% end %>

<%= link_to "New Listing", new_listing_path %>
<%= link_to "Show My Listing", my_listings_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render partial: "form" %>

app/views/listings/show.html.erb
<h1>Show Listing</h1>

<%= @listing.name %>

<% if current_user == @listing.user %>
	<%= link_to "Edit", edit_listing_path %>
	<%= button_to "Delete", listing_path, method: :delete, data: {confirm: "u sure?"} %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |u| %>
	<%= u.text_field :email, placeholder: "Email" %>
	<%= u.submit %>
<% end %>

<%= link_to "Login", login_path %>